// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: embeddings.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interests     []string               `protobuf:"bytes,1,rep,name=interests,proto3" json:"interests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterestsRequest) Reset() {
	*x = InterestsRequest{}
	mi := &file_embeddings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterestsRequest) ProtoMessage() {}

func (x *InterestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embeddings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterestsRequest.ProtoReflect.Descriptor instead.
func (*InterestsRequest) Descriptor() ([]byte, []int) {
	return file_embeddings_proto_rawDescGZIP(), []int{0}
}

func (x *InterestsRequest) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

type InterestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []float32              `protobuf:"fixed32,1,rep,packed,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterestsResponse) Reset() {
	*x = InterestsResponse{}
	mi := &file_embeddings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterestsResponse) ProtoMessage() {}

func (x *InterestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embeddings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterestsResponse.ProtoReflect.Descriptor instead.
func (*InterestsResponse) Descriptor() ([]byte, []int) {
	return file_embeddings_proto_rawDescGZIP(), []int{1}
}

func (x *InterestsResponse) GetEmbeddings() []float32 {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

var File_embeddings_proto protoreflect.FileDescriptor

const file_embeddings_proto_rawDesc = "" +
	"\n" +
	"\x10embeddings.proto\"0\n" +
	"\x10InterestsRequest\x12\x1c\n" +
	"\tinterests\x18\x01 \x03(\tR\tinterests\"3\n" +
	"\x11InterestsResponse\x12\x1e\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\x02R\n" +
	"embeddings2K\n" +
	"\x11EmbeddingsService\x126\n" +
	"\rGetEmbeddings\x12\x11.InterestsRequest\x1a\x12.InterestsResponseB\x0fZ\rbackend/protob\x06proto3"

var (
	file_embeddings_proto_rawDescOnce sync.Once
	file_embeddings_proto_rawDescData []byte
)

func file_embeddings_proto_rawDescGZIP() []byte {
	file_embeddings_proto_rawDescOnce.Do(func() {
		file_embeddings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embeddings_proto_rawDesc), len(file_embeddings_proto_rawDesc)))
	})
	return file_embeddings_proto_rawDescData
}

var file_embeddings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_embeddings_proto_goTypes = []any{
	(*InterestsRequest)(nil),  // 0: InterestsRequest
	(*InterestsResponse)(nil), // 1: InterestsResponse
}
var file_embeddings_proto_depIdxs = []int32{
	0, // 0: EmbeddingsService.GetEmbeddings:input_type -> InterestsRequest
	1, // 1: EmbeddingsService.GetEmbeddings:output_type -> InterestsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_embeddings_proto_init() }
func file_embeddings_proto_init() {
	if File_embeddings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embeddings_proto_rawDesc), len(file_embeddings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embeddings_proto_goTypes,
		DependencyIndexes: file_embeddings_proto_depIdxs,
		MessageInfos:      file_embeddings_proto_msgTypes,
	}.Build()
	File_embeddings_proto = out.File
	file_embeddings_proto_goTypes = nil
	file_embeddings_proto_depIdxs = nil
}
