# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/embeddings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/embeddings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/embeddings.proto\"%\n\x10InterestsRequest\x12\x11\n\tinterests\x18\x01 \x03(\t\"\'\n\x11InterestsResponse\x12\x12\n\nembeddings\x18\x01 \x03(\x02\x32K\n\x11\x45mbeddingsService\x12\x36\n\rGetEmbeddings\x12\x11.InterestsRequest\x1a\x12.InterestsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.embeddings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTERESTSREQUEST']._serialized_start=26
  _globals['_INTERESTSREQUEST']._serialized_end=63
  _globals['_INTERESTSRESPONSE']._serialized_start=65
  _globals['_INTERESTSRESPONSE']._serialized_end=104
  _globals['_EMBEDDINGSSERVICE']._serialized_start=106
  _globals['_EMBEDDINGSSERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
